const fs = require('node:fs');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '../templates/reader.html'), 'utf8');
const start = source.indexOf('        const cbzImageQueue');
const end = source.indexOf('        // 加载PDF章节', start);
if (start < 0 || end < start) throw new Error('Reader queue not found');
const prelude = "const assert = require('node:assert/strict');\nconst timers = new Map(); let timerId = 0;\nglobal.window = {innerHeight:800,setTimeout(fn,ms){timers.set(++timerId,{fn,ms});return timerId;},clearTimeout(id){timers.delete(id);},scrollBy(){}};\nclass Element {\n constructor(){this.style={};this.dataset={};this.children=[];this.isConnected=true;this.naturalWidth=720;this.naturalHeight=1000;this.complete=false;}\n appendChild(e){this.children.push(e);} getBoundingClientRect(){return {top:0,bottom:1000};}\n addEventListener(){} remove(){} removeAttribute(name){delete this[name];}\n}\nglobal.document={hidden:false,addEventListener(){},createElement(){return new Element();},querySelectorAll(){return [];}};\nglobal.IntersectionObserver=class {observe(){} unobserve(){} };\nlet activeChapterLoadToken=1, currentMargin=0, continuousSections=[], isDraggingProgressSlider=false, currentChapter=0, currentChapterReady=false;\nconst pageContent={}; function queueProgressUiSync(){} function completePassedChapter(){}\nasync function waitForReaderVisible(){}\n";
const cases = "(async()=>{\n const cache={dimensions:[],pagesUrl:'/pages'};\n const pages=Array.from({length:6},(_,i)=>buildCbzPageContainer(cache,i,6,1,{}));\n pages.forEach((p,i)=>p.getBoundingClientRect=()=>({top:(i-3)*1000,bottom:(i-2)*1000}));\n queueCbzChapterImages({querySelectorAll(){return pages;}});\n await new Promise(setImmediate);\n assert.equal(pages.filter(p=>p.dataset.loading==='true').length,4);\n assert.equal(pages[3].dataset.loading,'true');assert.equal(pages[0].dataset.loading,undefined);\n // Completing a visible page starts a distant page even without any scroll/observer event.\n pages[3].children[0].onload();await new Promise(setImmediate);\n assert.equal(pages[5].dataset.loading,'true');\n pages[2].children[0].onload();await new Promise(setImmediate);\n assert.equal(pages[0].dataset.loading,'true');\n for(const p of pages.filter(p=>p.dataset.loading==='true'))p.children[0].onload();\n await new Promise(setImmediate);assert.equal(cbzImagesLoading,0);\n const failed=buildCbzPageContainer(cache,0,6,1,{});queueCbzImage(failed);await new Promise(setImmediate);\n failed.children[0].onerror();await new Promise(setImmediate);\n const retry=[...timers.values()].find(t=>t.ms===600);assert.ok(retry);retry.fn();await new Promise(setImmediate);\n assert.equal(failed.dataset.loading,'true');assert.match(failed.children[0].src,/retry=/);\n failed.children[0].onload();await new Promise(setImmediate);\n const stalled=buildCbzPageContainer(cache,0,6,1,{});queueCbzImage(stalled);await new Promise(setImmediate);\n const watchdog=[...timers.values()].find(t=>t.ms===45000);assert.ok(watchdog);watchdog.fn();await new Promise(setImmediate);\n assert.equal(stalled.dataset.loading,'error');assert.equal(cbzImagesLoading,0);\n const cancelled=buildCbzPageContainer(cache,0,6,1,{});queueCbzImage(cancelled);await new Promise(setImmediate);\n cancelled.cancelImageLoad();await new Promise(setImmediate);assert.equal(cbzImagesLoading,0);\n console.log('Reader: four parallel loads, nearby priority, whole-chapter loading without scrolling, retry and timeout recovery passed');\n})();\n";
new Function('require', prelude + source.slice(start, end) + cases)(require);
